AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Benchmarking

Parameters:
  NodeEightGeneratorStack:
    Type: String
    Default: lambda-benchmarking-node8-generators
    AllowedPattern: "[A-Za-z0-9-]+"

  JavaEightGeneratorStack:
    Type: String
    Default: lambda-benchmarking-java8-generators
    AllowedPattern: "[A-Za-z0-9-]+"

  SlackUrl:
    Type: String
    NoEcho: true

Resources:
  # This holds all historical data, so be careful if making changes.
  Bucket:
    Type: AWS::S3::Bucket
  
  TimingsCollector:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/timingsCollector.handler
      Runtime: nodejs8.10
      MemorySize: 1024
      CodeUri: ./target
      Timeout: 60
      Environment:
        Variables:
          BUCKET_NAME: !Ref Bucket
          NODE8_GENERATOR_STACK_NAME: !Ref NodeEightGeneratorStack
          JAVA8_GENERATOR_STACK_NAME: !Ref JavaEightGeneratorStack
      Events:
        TenPastHour:
          Type: Schedule
          Properties:
            Schedule: cron(10 1/4 * * ? *)
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - xray:BatchGetTraces
          - xray:GetTraceSummaries
          Resource: '*'
        - Effect: Allow
          Action:
          - s3:putObject
          Resource: !Sub ${Bucket.Arn}/*
        - Effect: Allow
          Action:
          - s3:ListBucket
          Resource: !Sub ${Bucket.Arn}
        - Effect: Allow
          Action:
          - cloudformation:ListStackResources
          Resource:
          - !Sub arn:aws:cloudformation:us-east-1:${AWS::AccountId}:stack/${NodeEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:us-east-2:${AWS::AccountId}:stack/${NodeEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:us-west-1:${AWS::AccountId}:stack/${NodeEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:us-west-2:${AWS::AccountId}:stack/${NodeEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:eu-central-1:${AWS::AccountId}:stack/${NodeEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:eu-west-1:${AWS::AccountId}:stack/${NodeEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:eu-west-2:${AWS::AccountId}:stack/${NodeEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:eu-west-3:${AWS::AccountId}:stack/${NodeEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:us-east-1:${AWS::AccountId}:stack/${JavaEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:us-east-2:${AWS::AccountId}:stack/${JavaEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:us-west-1:${AWS::AccountId}:stack/${JavaEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:us-west-2:${AWS::AccountId}:stack/${JavaEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:eu-central-1:${AWS::AccountId}:stack/${JavaEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:eu-west-1:${AWS::AccountId}:stack/${JavaEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:eu-west-2:${AWS::AccountId}:stack/${JavaEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:eu-west-3:${AWS::AccountId}:stack/${JavaEightGeneratorStack}/*

  TimingsCollectorErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Track Errors for TimingsCollector
      Namespace: 'AWS/Lambda'
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref TimingsCollector
      Statistic: Sum
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      Period: 600
      EvaluationPeriods: 1
      TreatMissingData: "notBreaching"
      ActionsEnabled: True
      AlarmActions:
        - !Ref ErrorsTopic
      OKActions:
        - !Ref ErrorsTopic

  ErrorsTopic:
    Type: AWS::SNS::Topic

  SlackErrorNotifier:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/slackErrorNotifier.handler
      Runtime: nodejs8.10
      MemorySize: 256
      CodeUri: ./target
      Timeout: 20
      Environment:
        Variables:
          SLACK_URL: !Ref SlackUrl
          SLACK_CHANNEL: lambda-benchmarking
      Events:
        ErrorsTopic:
          Type: SNS
          Properties:
            Topic: !Ref ErrorsTopic 

  GeneratorInvoker:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/generatorInvoker.handler
      Runtime: nodejs8.10
      MemorySize: 512
      CodeUri: ./target
      Timeout: 60
      Environment:
        Variables:
          NODE8_GENERATOR_STACK_NAME: !Ref NodeEightGeneratorStack
          JAVA8_GENERATOR_STACK_NAME: !Ref JavaEightGeneratorStack
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - lambda:InvokeFunction
          Resource: '*'
        - Effect: Allow
          Action:
          - cloudformation:ListStackResources
          Resource:
          - !Sub arn:aws:cloudformation:us-east-1:${AWS::AccountId}:stack/${NodeEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:us-east-2:${AWS::AccountId}:stack/${NodeEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:us-west-1:${AWS::AccountId}:stack/${NodeEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:us-west-2:${AWS::AccountId}:stack/${NodeEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:eu-central-1:${AWS::AccountId}:stack/${NodeEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:eu-west-1:${AWS::AccountId}:stack/${NodeEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:eu-west-2:${AWS::AccountId}:stack/${NodeEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:eu-west-3:${AWS::AccountId}:stack/${NodeEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:us-east-1:${AWS::AccountId}:stack/${JavaEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:us-east-2:${AWS::AccountId}:stack/${JavaEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:us-west-1:${AWS::AccountId}:stack/${JavaEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:us-west-2:${AWS::AccountId}:stack/${JavaEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:eu-central-1:${AWS::AccountId}:stack/${JavaEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:eu-west-1:${AWS::AccountId}:stack/${JavaEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:eu-west-2:${AWS::AccountId}:stack/${JavaEightGeneratorStack}/*
          - !Sub arn:aws:cloudformation:eu-west-3:${AWS::AccountId}:stack/${JavaEightGeneratorStack}/*
